---
- hosts: all
  remote_user: ansible
  become: true
  tasks:
  - name: install DOCKER if UBUNTU
    command: "{{ item }}"
    loop:
      - sudo apt install docker.io -y
      - sudo apt-get update

